### ISSUE TITLE
Error with Completion Exception from DynamicLights

### ISSUE THREAD

**Issue by suerion** [Tschipcraft/dynamiclights#60]
### Describe the bug

Describe the bug
Hey, i got some issues on my side with completionException:
Fabric 1.21.1 on 0.16.5
```
[15:29:01] [main/ERROR]: Failed to load function dynamiclights:reset
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 17: Could not parse command: Mixin transformation of net.minecraft.command.argument.MessageArgumentType$MessageFormat failed at position 4: say <--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 17: Could not parse command: Mixin transformation of net.minecraft.command.argument.MessageArgumentType$MessageFormat failed at position 4: say <--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
[15:29:01] [main/ERROR]: Failed to load function dynamiclights:settings/hide_feedback/hide
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Expected whitespace to end one argument, but found trailing data at position 13: ...erule send<--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Expected whitespace to end one argument, but found trailing data at position 13: ...erule send<--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
[15:29:01] [main/ERROR]: Failed to load function dynamiclights:settings/hide_feedback/unhide
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Expected whitespace to end one argument, but found trailing data at position 13: ...erule send<--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Expected whitespace to end one argument, but found trailing data at position 13: ...erule send<--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
[15:29:01] [main/ERROR]: Failed to load function dynamiclights:uninstall
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 42: Could not parse command: Mixin transformation of net.minecraft.command.argument.MessageArgumentType$MessageFormat failed at position 4: say <--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 42: Could not parse command: Mixin transformation of net.minecraft.command.argument.MessageArgumentType$MessageFormat failed at position 4: say <--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
[15:29:01] [main/ERROR]: Failed to load function dynamiclights:settings/hide_feedback/main
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 4: Expected whitespace to end one argument, but found trailing data at position 83: ...erule send<--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 4: Expected whitespace to end one argument, but found trailing data at position 83: ...erule send<--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
```

### Steps to reproduce

Hugh Modpack Server Log:
https://mclo.gs/iKlXez6

### Expected behavior

Commands should work fine.

**Comment by vgrynch** [comment]
Ok, I have changed the setting `function-permission-level` to 2 in the Minecraft properties file and it all started to work. Paper server sets this to 1.

Recommendation to the data pack developer: Please mention the above in the data pack description.

**Comment by vgrynch** [comment]
It was not Paper, sorry. We switched to Paper later, after using some other server types, some of which could set this default to 1 initially. Sorry for misleading.
